SW-4259 'Observation not scheduled' notification emails to Terraformation Contact/Support
terraware/terraware-server pull request #1386
Opened 2023-10-03 12:14 UTC by karthikbtf

- Send email notifications to Terraformation Contact (or Terraformation Support) when observations haven't been scheduled in a while
- First notification is sent when 8 weeks have elapsed since the last completed observation (or 6 weeks since the first planting)
- Second notification is sent when 16 weeks have elapsed since the last completed observation (or 14 weeks since the first planting)
- Added a support config in TerrawareServerConfig to configure a support email
- Email is sent to the org's Terraformation Contact user if one exists, otherwise to the support email (if configured)
- Added tests
- Tested locally with the test clock, had to increase test clock html input to 3 (to advance clock to 16 weeks)
- There is no app notification for this use case

2023-10-03 15:54 UTC, sgrimm requested changes
Just some small stuff; generally this looks fine, though I worry that we're now accumulating a lot of nearly-identical notification functions.

2023-10-03 15:54 UTC, sgrimm commented on src/main/kotlin/com/terraformation/backend/email/EmailNotificationService.kt
> +    // return if we don't have a TF contact to send email to
This comment seems inaccurate

2023-10-03 15:54 UTC, sgrimm commented on src/main/kotlin/com/terraformation/backend/email/EmailNotificationService.kt
> +    user?.let {
I think `if (user != null)` would probably be a bit easier to read here than the `let` expression.

2023-10-03 15:54 UTC, sgrimm commented on src/main/kotlin/com/terraformation/backend/email/EmailService.kt
> +    config.support.email?.let { Locale.ENGLISH.use { send(model, listOf(it)) } }
The use of `it` is slightly unclear here since it's in a nested lambda. Maybe introduce a name for it like `email`?

2023-10-03 15:54 UTC, sgrimm commented on src/main/kotlin/com/terraformation/backend/tracking/db/PlantingSiteStore.kt
> +        .where(PLANTING_SITES.ID.eq(plantingSiteId))
There are now enough of these that I wonder if it makes sense to refactor them to call a helper method that takes the timestamp field to update as an argument.

2023-10-03 15:54 UTC, sgrimm commented on src/main/resources/i18n/Messages_en.properties
> +
Blank line will get removed by Phrase

2023-10-11 09:13 UTC, karthikbtf commented
> Just some small stuff; generally this looks fine, though I worry that we're now accumulating a lot of nearly-identical notification functions.

Thanks again for the feedback, applied the changes. Also modified the parent PR to remove the various almost identical functions, which I agree was not too pretty. Updated this PR to leverage the criteria model in the parent PR.

2023-10-11 15:57 UTC, sgrimm approved these changes
Looks good, but of course if you go with my naming suggestions on the parent PR, this one should change too. If not, this is good to go as-is once the parent is merged.

2023-10-12 03:38 UTC, merged