Add permissions for interacting with the participant_project_species
terraware/terraware-server pull request #1917
Opened 2024-05-01 20:01 UTC by nickgraz

2024-05-01 20:01 UTC, nickgraz commented
* **#1937** <a href="https://app.graphite.dev/github/pr/terraware/terraware-server/1937?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a>
* **#1935** <a href="https://app.graphite.dev/github/pr/terraware/terraware-server/1935?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a>
* **#1934** <a href="https://app.graphite.dev/github/pr/terraware/terraware-server/1934?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a>
* **#1933** <a href="https://app.graphite.dev/github/pr/terraware/terraware-server/1933?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a>
* **#1932** <a href="https://app.graphite.dev/github/pr/terraware/terraware-server/1932?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a>
* **#1924** <a href="https://app.graphite.dev/github/pr/terraware/terraware-server/1924?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a>
* **#1919** <a href="https://app.graphite.dev/github/pr/terraware/terraware-server/1919?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a>
* **#1918** <a href="https://app.graphite.dev/github/pr/terraware/terraware-server/1918?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a>
* **#1917** <a href="https://app.graphite.dev/github/pr/terraware/terraware-server/1917?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a> 👈
* **#1916** <a href="https://app.graphite.dev/github/pr/terraware/terraware-server/1916?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a>
* `main`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @nickgraz and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="11px" height="11px"/> <b>Graphite</b></a>
  <!-- Current dependencies on/for this PR: -->

2024-05-01 20:28 UTC, sgrimm requested changes
A couple minor things to fix here, but generally looks good. Obviously if you decide to use a compound primary key on the table, this PR will need to change too.

2024-05-01 20:28 UTC, sgrimm commented on src/test/kotlin/com/terraformation/backend/customer/model/PermissionTest.kt
> +    private val uncheckedParticipantProjectSpecies = participantProjectSpeciesIds.toMutableSet()
`andNothingElse()` needs to check the remaining IDs from this set.

2024-05-01 20:28 UTC, sgrimm commented on src/test/kotlin/com/terraformation/backend/db/DatabaseTest.kt
> +  private var nextParticipantProjectSpeciesNumber = 1
This doesn't seem to be used.

2024-05-01 20:28 UTC, sgrimm commented on src/test/kotlin/com/terraformation/backend/db/DatabaseTest.kt
> +    val participantProjectSpeciesIds = mutableListOf<ParticipantProjectSpeciesId>()
Maybe also add `participantProjectSpeciesId` to return the most recently-inserted ID?

2024-05-01 22:58 UTC, sgrimm approved these changes

2024-05-02 15:15 UTC, nickgraz commented
### Merge activity

* **May 2, 11:15 AM EDT**: @nickgraz started a stack merge that includes this pull request via [Graphite](https://app.graphite.dev/github/pr/terraware/terraware-server/1917).
* **May 2, 11:16 AM EDT**: [Graphite](https://app.graphite.dev/github/pr/terraware/terraware-server/1917) rebased this pull request as part of a merge.
* **May 2, 11:25 AM EDT**: @nickgraz merged this pull request with [Graphite](https://app.graphite.dev/github/pr/terraware/terraware-server/1917).

2024-05-02 15:25 UTC, merged