Added admin UI for managing due dates
terraware/terraware-server pull request #1966
Opened 2024-05-18 00:33 UTC by tommylau523

2024-05-18 00:33 UTC, tommylau523 commented
> [!WARNING]
> <b>This pull request is not mergeable via GitHub because a downstack PR is open. Once all requirements are satisfied, merge this PR as a stack <a href="https://app.graphite.dev/github/pr/terraware/terraware-server/1966?utm_source=stack-comment-downstack-mergeability-warning" >on Graphite</a>.</b>
> <a href="https://graphite.dev/docs/merge-pull-requests">Learn more</a>

* **#1966** <a href="https://app.graphite.dev/github/pr/terraware/terraware-server/1966?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a> 👈
* **#1965** <a href="https://app.graphite.dev/github/pr/terraware/terraware-server/1965?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a>
* **#1964** <a href="https://app.graphite.dev/github/pr/terraware/terraware-server/1964?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a>
* **#1963** <a href="https://app.graphite.dev/github/pr/terraware/terraware-server/1963?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a>
* **#1962** <a href="https://app.graphite.dev/github/pr/terraware/terraware-server/1962?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a>
* `main`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @tommylau523 and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="11px" height="11px"/> <b>Graphite</b></a>
  <!-- Current dependencies on/for this PR: -->

2024-05-20 15:48 UTC, sgrimm requested changes

2024-05-20 15:48 UTC, sgrimm commented on src/main/kotlin/com/terraformation/backend/admin/AdminCohortsController.kt
> +          redirectAttributes.failureMessage = "Error looking up deliverable due date: ${e.message}"
Logging the exception here would be useful.

2024-05-20 15:48 UTC, sgrimm commented on src/main/kotlin/com/terraformation/backend/admin/AdminCohortsController.kt
> +    model.addAttribute("canManageDeliverables", currentUser().canManageDeliverables())
The rest of the attributes are alphabetized, so may as well put this one at the top.

2024-05-20 15:48 UTC, sgrimm commented on src/main/kotlin/com/terraformation/backend/admin/AdminCohortsController.kt
> +    when (operation) {
This could use a try/catch to show a failure message in case one of the write functions throws an exception.

2024-05-20 19:33 UTC, sgrimm approved these changes

2024-05-20 20:19 UTC, tommylau523 commented
### Merge activity

* **May 20, 4:19 PM EDT**: [Graphite](https://app.graphite.dev/github/pr/terraware/terraware-server/1966) rebased this pull request as part of a merge.

2024-05-20 20:28 UTC, merged