Send notifications for variables reviews
terraware/terraware-server pull request #2137
Opened 2024-07-09 20:55 UTC by tommylau523

2024-07-09 20:55 UTC, tommylau523 commented
* **#2137** <a href="https://app.graphite.dev/github/pr/terraware/terraware-server/2137?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a> 👈
* `main`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @tommylau523 and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="11px" height="11px"/> <b>Graphite</b></a>
  <!-- Current dependencies on/for this PR: -->

2024-07-10 00:01 UTC, sgrimm requested changes

2024-07-10 00:01 UTC, sgrimm commented on src/main/kotlin/com/terraformation/backend/accelerator/SubmissionNotifier.kt
> +   * Publishes [QuestionsDeliverableStatusUpdatedEvent] if not user-visible feedback or status has
Nit: "not" should be "no"

2024-07-10 00:01 UTC, sgrimm commented on src/main/kotlin/com/terraformation/backend/accelerator/SubmissionNotifier.kt
> +          }
This seems like it'll be fetching a bunch of data only to throw most of it away. Alternative would be to add a fetch method that takes both a project and a deliverable ID and does this filtering in the database query.

(But maybe this isn't needed at all; see my comment below about an alternative way of detecting recent changes.)

2024-07-10 00:01 UTC, sgrimm commented on src/main/kotlin/com/terraformation/backend/accelerator/SubmissionNotifier.kt
> +            val deliverableWorkflow = event.currentWorkflows[it.key]
Instead of `it.key` and `it.value`, this could use destructuring to declare named variables, like `.all { (variableId, historyModel) -> ... }`

2024-07-10 00:01 UTC, sgrimm commented on src/main/kotlin/com/terraformation/backend/documentproducer/event/QuestionsDeliverableReviewedEvent.kt
> +    val currentWorkflows: Map<VariableId, ExistingVariableWorkflowHistoryModel>,
It looks to me like this map is being used to compare against the latest data to detect if anything has changed.

If that's the case, then it might be more efficient to replace this with a workflow history ID, and then the "has anything new happened" check goes from a map fetch and comparison to an "exists" query that checks whether there are greater workflow history IDs for variables with the same project + deliverable.

2024-07-10 00:04 UTC, tommylau523 commented on src/main/kotlin/com/terraformation/backend/documentproducer/event/QuestionsDeliverableReviewedEvent.kt
> +    val currentWorkflows: Map<VariableId, ExistingVariableWorkflowHistoryModel>,
The tricky bit is that we don't want to notify users if it is only an internal comment update. So the payload is all added to allow for the check of if status or feedback have changed down the line.

2024-07-10 00:07 UTC, tommylau523 commented on src/main/kotlin/com/terraformation/backend/documentproducer/event/QuestionsDeliverableReviewedEvent.kt
> +    val currentWorkflows: Map<VariableId, ExistingVariableWorkflowHistoryModel>,
But in addition to that, I suspect that we probably want some sort of changelogs for email notifications/in app screen (still need designs according to PRD). Maybe a better approach is to keep track of a "last-notified", and batch a bunch of history changes together and notify that way.

2024-07-10 15:00 UTC, sgrimm commented on src/main/kotlin/com/terraformation/backend/documentproducer/event/QuestionsDeliverableReviewedEvent.kt
> +    val currentWorkflows: Map<VariableId, ExistingVariableWorkflowHistoryModel>,
Good point about internal comment updates. In that case this approach is reasonable for now.

2024-07-10 19:17 UTC, tommylau523 commented on src/main/kotlin/com/terraformation/backend/accelerator/SubmissionNotifier.kt
> +          }
Added a fetch method for this!

2024-07-10 22:39 UTC, sgrimm approved these changes

2024-07-10 22:56 UTC, tommylau523 commented
### Merge activity

* **Jul 10, 6:56 PM EDT**: @tommylau523 started a stack merge that includes this pull request via [Graphite](https://app.graphite.dev/github/pr/terraware/terraware-server/2137).

2024-07-10 22:57 UTC, merged