Implemented notifications for application submission
terraware/terraware-server pull request #2361
Opened 2024-09-03 21:28 UTC by tommylau523

2024-09-03 21:29 UTC, tommylau523 commented
> [!WARNING]
> <b>This pull request is not mergeable via GitHub because a downstack PR is open. Once all requirements are satisfied, merge this PR as a stack <a href="https://app.graphite.dev/github/pr/terraware/terraware-server/2361?utm_source=stack-comment-downstack-mergeability-warning" >on Graphite</a>.</b>
> <a href="https://graphite.dev/docs/merge-pull-requests">Learn more</a>

* **#2361** <a href="https://app.graphite.dev/github/pr/terraware/terraware-server/2361?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a> 👈
* **#2360** <a href="https://app.graphite.dev/github/pr/terraware/terraware-server/2360?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a>
* **#2359** <a href="https://app.graphite.dev/github/pr/terraware/terraware-server/2359?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a>
* **#2358** <a href="https://app.graphite.dev/github/pr/terraware/terraware-server/2358?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a>
* **#2347** <a href="https://app.graphite.dev/github/pr/terraware/terraware-server/2347?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a>: 1 other dependent PR ([#2348](https://github.com/terraware/terraware-server/pull/2348) <a href="https://app.graphite.dev/github/pr/terraware/terraware-server/2348?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a>)
* `main`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @tommylau523 and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="11px" height="11px"/> <b>Graphite</b></a>
  <!-- Current dependencies on/for this PR: -->

2024-09-03 21:29 UTC, tommylau523 commented
> [!WARNING]
> <b>This pull request is not mergeable via GitHub because a downstack PR is open. Once all requirements are satisfied, merge this PR as a stack <a href="https://app.graphite.dev/github/pr/terraware/terraware-server/2361?utm_source=stack-comment-downstack-mergeability-warning" >on Graphite</a>.</b>
> <a href="https://graphite.dev/docs/merge-pull-requests">Learn more</a>

* **#2361** <a href="https://app.graphite.dev/github/pr/terraware/terraware-server/2361?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a> 👈
* **#2360** <a href="https://app.graphite.dev/github/pr/terraware/terraware-server/2360?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a>
* **#2359** <a href="https://app.graphite.dev/github/pr/terraware/terraware-server/2359?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a>
* **#2358** <a href="https://app.graphite.dev/github/pr/terraware/terraware-server/2358?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a>
* **#2347** <a href="https://app.graphite.dev/github/pr/terraware/terraware-server/2347?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a>: 1 other dependent PR ([#2348](https://github.com/terraware/terraware-server/pull/2348) <a href="https://app.graphite.dev/github/pr/terraware/terraware-server/2348?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a>)
* `main`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @tommylau523 and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="11px" height="11px"/> <b>Graphite</b></a>
  <!-- Current dependencies on/for this PR: -->

2024-09-03 21:29 UTC, tommylau523 commented
> [!WARNING]
> <b>This pull request is not mergeable via GitHub because a downstack PR is open. Once all requirements are satisfied, merge this PR as a stack <a href="https://app.graphite.dev/github/pr/terraware/terraware-server/2361?utm_source=stack-comment-downstack-mergeability-warning" >on Graphite</a>.</b>
> <a href="https://graphite.dev/docs/merge-pull-requests">Learn more</a>

* **#2361** <a href="https://app.graphite.dev/github/pr/terraware/terraware-server/2361?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a> 👈
* **#2360** <a href="https://app.graphite.dev/github/pr/terraware/terraware-server/2360?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a>
* **#2359** <a href="https://app.graphite.dev/github/pr/terraware/terraware-server/2359?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a>
* **#2358** <a href="https://app.graphite.dev/github/pr/terraware/terraware-server/2358?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a>
* **#2347** <a href="https://app.graphite.dev/github/pr/terraware/terraware-server/2347?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a>: 1 other dependent PR ([#2348](https://github.com/terraware/terraware-server/pull/2348) <a href="https://app.graphite.dev/github/pr/terraware/terraware-server/2348?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a>)
* `main`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @tommylau523 and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="11px" height="11px"/> <b>Graphite</b></a>
  <!-- Current dependencies on/for this PR: -->

2024-09-03 21:39 UTC, sgrimm commented on src/main/kotlin/com/terraformation/backend/i18n/Messages.kt
> +              "notification.application.submitted.app.body", organizationName, timeSubmitted),
The time doesn't appear to be used. The message only has a `{0}` placeholder, no `{1}`.

2024-09-03 22:15 UTC, sgrimm requested changes

2024-09-03 22:15 UTC, sgrimm commented on src/main/resources/i18n/Messages_en.properties
> +notification.application.submitted.email.buttonLabel=View Application.
The period at the end doesn't seem right for a button label.

2024-09-03 22:15 UTC, sgrimm commented on src/main/kotlin/com/terraformation/backend/customer/AppNotificationService.kt
> +        messages.applicationSubmittedNotification(organization.name, event.time)
The time is unused.

2024-09-03 23:32 UTC, sgrimm requested changes
EmailNotificationService seems to have a lot of unnecessary changes. I assume it's IntelliJ doing an automated edit or somesuch.

2024-09-03 23:32 UTC, sgrimm commented on src/main/kotlin/com/terraformation/backend/email/EmailNotificationService.kt
> +                event.facilityId,
Why all the added trailing commas?

2024-09-03 23:35 UTC, tommylau523 commented
Not sure how that happened. Maybe something with kfmt. Let me try to revert some of these.

2024-09-04 00:25 UTC, sgrimm approved these changes

2024-09-04 00:25 UTC, sgrimm commented on src/main/kotlin/com/terraformation/backend/email/model/Models.kt
> +            DefaultObjectWrapperBuilder(Configuration.VERSION_2_3_31).build(),
Another stray trailing comma.

2024-09-04 00:41 UTC, tommylau523 commented
### Merge activity

* **Sep 3, 8:41 PM EDT**: @tommylau523 started a stack merge that includes this pull request via [Graphite](https://app.graphite.dev/github/pr/terraware/terraware-server/2361).

2024-09-04 01:25 UTC, merged