Added TFContact userID to organization payload
terraware/terraware-server pull request #2387
Opened 2024-09-06 19:22 UTC by tommylau523

2024-09-06 19:22 UTC, tommylau523 commented
* **#2387** <a href="https://app.graphite.dev/github/pr/terraware/terraware-server/2387?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a> 👈
* `main`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @tommylau523 and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="11px" height="11px"/> <b>Graphite</b></a>
  <!-- Current dependencies on/for this PR: -->

2024-09-06 19:34 UTC, sgrimm requested changes
I think we can add a permission check here without too much pain so that we're not exposing this user ID to users who don't have permission to see which users are in the organization.

Easiest (and reasonable, I think, in terms of product behavior) would be to make `fetchTerraformationContact` return null if the user lacks "can list organization users" permission, and then modify that permission check so it returns true for internal people if the organization is an accelerator-tagged one, which there's a helper function for. Something like,
```
  override fun canListOrganizationUsers(organizationId: OrganizationId) =
      isManagerOrHigher(organizationId) || isGlobalReader(organizationId)
```

2024-09-06 19:34 UTC, sgrimm commented on src/main/kotlin/com/terraformation/backend/customer/api/OrganizationsController.kt
> +    val tfContactUserId: UserId?,
This should go above the `@Schema` since the description there is for `totalUsers`.

2024-09-06 21:27 UTC, sgrimm requested changes
This needs to update `IndividualUser.canListOrganizationUsers` (see my previous comment on the PR) or it will return a permission error for accelerator admins who aren't admins of the org in question.

2024-09-06 21:27 UTC, sgrimm commented on src/test/kotlin/com/terraformation/backend/customer/db/OrganizationStoreTest.kt
> +  fun `fetchTerraformationContact throws exception if no permission ot list organization users`() {
Nit: "ot" instead of "to"

2024-09-09 15:44 UTC, sgrimm commented
Test failures seem legitimate here.

2024-09-09 20:43 UTC, sgrimm approved these changes
PR title could use an update to reflect the fact that this moved to a different payload, but looks good otherwise with a couple nits (one from an earlier review, one new one).

2024-09-09 20:43 UTC, sgrimm commented on src/test/kotlin/com/terraformation/backend/customer/model/PermissionTest.kt
> +        listOrganizationUsers = true,
Alphabetize these for consistency with the other expect functions.

2024-09-09 21:14 UTC, closed without merging

2024-09-09 21:15 UTC, tommylau523 commented
### Merge activity

* **Sep 9, 5:15 PM EDT**: [Graphite](https://app.graphite.dev/github/pr/terraware/terraware-server/2387) couldn't merge this PR because it failed for an unknown reason.