Fetch observations by ad-hoc flag
terraware/terraware-server pull request #2688
Opened 2024-12-13 01:30 UTC by tommylau523

2024-12-13 01:52 UTC, tommylau523 commented
* **#2688** <a href="https://app.graphite.dev/github/pr/terraware/terraware-server/2688?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a> 👈 <a href="https://app.graphite.dev/github/pr/terraware/terraware-server/2688?utm_source=stack-comment-view-in-graphite" target="_blank">(View in Graphite)</a>
* `main`


<h2></h2>

This stack of pull requests is managed by <a href="https://graphite.dev?utm-source=stack-comment"><b>Graphite</b></a>. Learn more about <a href="https://stacking.dev/?utm_source=stack-comment">stacking</a>.
<!-- Current dependencies on/for this PR: -->

2024-12-13 22:10 UTC, sgrimm requested changes
Seems good generally, with a couple nits and one change to improve query efficiency.

2024-12-13 22:10 UTC, sgrimm commented on src/main/kotlin/com/terraformation/backend/tracking/api/ObservationsController.kt
> +  @Operation(summary = "Gets a list of observations of planting sites.")
Including "ad-hoc" in the summary would make it clearer.

2024-12-13 22:10 UTC, sgrimm commented on src/main/kotlin/com/terraformation/backend/tracking/api/ObservationsController.kt
> +      plotCounts = observationStore.countPlots(plantingSiteId)
Maybe this should take an argument to control whether it's counting plots in ad-hoc or assigned observations so we don't waste database time counting plots for observations we'll ignore.

2024-12-13 22:10 UTC, sgrimm commented on src/main/kotlin/com/terraformation/backend/tracking/api/ObservationsController.kt
> +    val plotId: MonitoringPlotId
May as well toss a trailing comma on here.

2024-12-17 19:34 UTC, sgrimm commented on src/main/kotlin/com/terraformation/backend/tracking/api/ObservationsController.kt
> +      plantingSiteId: PlantingSiteId? = null,
Not needed. Springdoc-openapi detects the nullable type automatically.

2024-12-17 19:36 UTC, sgrimm approved these changes

2024-12-17 21:28 UTC, tommylau523 commented
### Merge activity

* **Dec 17, 4:28 PM EST**: A user started a stack merge that includes this pull request via [Graphite](https://app.graphite.dev/github/pr/terraware/terraware-server/2688).

2024-12-17 22:05 UTC, merged